### ISSUE TITLE
I Can't connect to nord server! why?

### ISSUE THREAD

**Issue by najafice** [zBlxxded/NordVPN-Checker#1]
When I run the code, this message appeared:

```
[BlxxdChecker] » ¡ERROR! Check your internet connection or your IP and try again. 

Traceback (most recent call last):
  File "c:/Users/****/Desktop/Nord Setup/BlxxdNordVPNChecker-eng.py", line 98, in <module>
    main()
  File "c:/Users/****/Desktop/Nord Setup/BlxxdNordVPNChecker-eng.py", line 39, in main    
    if "\"token\":" in login(combo):
TypeError: argument of type 'NoneType' is not iterable
```
But I can open the URL's with my browser and I haven't any connection problem!
![image](https://user-images.githubusercontent.com/46795285/130229069-bdad6a92-e236-40f2-b591-2ca55a99576a.png)
How can i fix this?

**Comment by zBlxxded** [comment]
You are being rate limited, that API is not mine so I cannot do anything to it. I'll try to update this script adding proxies.
