### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aliafshany** [zBlxxded/NordVPN-Checker#2]
hi there

i experiance an issue

i was able to run it for a few times but now after changing multiple proxies i still get this error:

[BlxxdChecker] » ¡ERROR! Check your internet connection or your IP and try again. 

Traceback (most recent call last):
  File "/Users/**/Documents/NordVPN-Checker-main/BlxxdNordVPNChecker-eng.py", line 98, in <module>
    main()
  File "/Users/**/Documents/NordVPN-Checker-main/BlxxdNordVPNChecker-eng.py", line 39, in main
    if "\"token\":" in login(combo):
TypeError: argument of type 'NoneType' is not iterable

best

**Comment by zBlxxded** [comment]
You are being rate limited, that API is not mine so I cannot do anything to it. I'll try to update this script adding proxies.

**Comment by aliafshany** [comment]
no it is not related to ip ban
because i have used many IPs still the same.

it simply can not open the URL on the script.
